GET http://localhost:8080
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Сырники из творога",
  "cookingTime": 30,
  "ingredients": [
    {
      "title": "творог",
      "quantity": 350,
      "measureUnit": "грамм"
    },
    {
      "title": "куриное яйцо",
      "quantity": 2,
      "measureUnit": "штука"
    },
    {
      "title": "пшеничная мука",
      "quantity": 6,
      "measureUnit": "столовая ложка"
    },
    {
      "title": "сахар",
      "quantity": 2,
      "measureUnit": "столовая ложка"
    }
  ],
  "steps": [
    "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте",
    "Всыпьте в творог муку и тщательно перемешайте",
    "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло",
    "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду",
    "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния",
    "Повторяйте, пока творог не закончится"
  ]
}